# Copied from https://github.com/rerun-io/rerun_template
#

# -----------------------------------------------------------------------------

msrv = "1.96.0"

allow-unwrap-in-tests = true

# https://doc.rust-lang.org/nightly/clippy/lint_configuration.html#avoid-breaking-exported-api
# We want suggestions, even if it changes public API.
avoid-breaking-exported-api = false

excessive-nesting-threshold = 8

max-fn-params-bools = 1

# https://rust-lang.github.io/rust-clippy/master/index.html#/large_include_file
max-include-file-size = 1000000

# https://rust-lang.github.io/rust-clippy/master/index.html#/large_stack_frames
stack-size-threshold = 512000

too-many-lines-threshold = 200

# -----------------------------------------------------------------------------

# https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_macros
disallowed-macros = ['std::dbg']

# https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_methods
disallowed-methods = [
  { path = "std::env::temp_dir", reason = "Use the tempdir crate instead" },
  { path = "std::thread::spawn", reason = "Use `std::thread::Builder` and name the thread" },
]

# https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_names
disallowed-names = []

# https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_types
disallowed-types = [

  { path = "std::sync::Condvar", reason = "Use parking_lot instead" },
  { path = "std::sync::Mutex", reason = "Use parking_lot instead" },
  { path = "std::sync::RwLock", reason = "Use parking_lot instead" },

  # "std::sync::Once",  # enabled for now as the `log_once` macro uses it internally
]

# Allow-list of words for markdown in docstrings https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown
doc-valid-idents = [
  "GitHub",
  "KiB",
  "MiB",
  "QoS",
  "RSS",
  "GLB",
  "GLTF",
  "iOS",
  "macOS",
  "NaN",
  "OBJ",
  "OpenGL",
  "PyPI",
  "sRGB",
  "sRGBA",
  "WebGL",
  "WebSocket",
  "WebSockets",
]
